language: minimal
#language: node_js
#
#node_js: '10.0.0' # or another
#
#cache: npm

sudo: required
#services:
#  - docker
script:
  - docker-compose -f ./docker-compose-build.yml pull
  - docker-compose -f ./docker-compose-build.yml build
  - docker-compose ps


before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: bash deploy_service.sh
  on:
    branch: master