sudo: required
services:
  - docker
script:
  - docker-compose build
  - docker-compose bundle
  - docker-compose ls


before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: bash deploy_service.sh
  on:
    branch: master