language: minimal

sudo: required

script:
  - docker-compose -f ./docker-compose-build.yml pull
  - docker-compose -f ./docker-compose-build.yml build
  - docker-compose ps


before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: bash deploy_service.sh
  on:
    branch: master

# now to configure notifications
# https://docs.travis-ci.com/user/notifications/#changing-notification-frequency
notifications:
  email:
    on_success: never # default: always