version: '3.3'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  server:
    container_name: server
    build: ./backend
    image: wisehackermonkey/backend:latest
    command: npm start
    volumes:
      - ./server/:/usr/server
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  client:
    container_name: client
    build: ./frontend
    image: wisehackermonkey/frontend:latest
    command: npm start
    volumes:
      - ./frontend/:/usr/frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - server